# there may be other dependencies manually ignored.
# search `"@dependabot ignore" in:comments` in the repo to see them.
#
# reference:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      # only do patch updates for containerd and co: don't bump anything else
      - dependency-name: "github.com/containerd/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    # allow more PRs to clear queue faster
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - dependencies
      - go
      - tests
    ignore:
      # keep containerd and related dependencies in sync with the shim/the root repo
      - dependency-name: "github.com/containerd/*"
      # ignore patch version increment updates in test; they shouldn't be critical
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
